const { DataTypes } = require("sequelize");
const { sequelize } = require("../util/database");

module.exports = {
  Lead: sequelize.define("lead", {
    id: {
      type: DataTypes.INTEGER,
      autoIncrement: true,
      autoNull: false,
      primaryKey: true,
    },
    firstName: DataTypes.STRING,
    lastName: DataTypes.STRING,
    address: DataTypes.STRING,
    city: DataTypes.STRING,
    state: DataTypes.STRING,
    zipcode: DataTypes.STRING,
    email: DataTypes.STRING,
    phone: DataTypes.STRING,
    useage: DataTypes.STRING,
    income: DataTypes.STRING,
    credit: DataTypes.STRING,
    spouse: DataTypes.STRING,
    lender: DataTypes.STRING,
    pool: DataTypes.STRING,
    ev: DataTypes.STRING,
    occupants: DataTypes.STRING,
    ownerage: DataTypes.STRING,
    roofage: DataTypes.STRING,
    hoa: DataTypes.STRING,
    hoaName: DataTypes.STRING,
    hoaPhone: DataTypes.STRING,
    hoaEmail: DataTypes.STRING,
    hoaWebsite: DataTypes.STRING,
    hoaPresidentName: DataTypes.STRING,
    comments: DataTypes.STRING,
    appointment: DataTypes.STRING,
    time: DataTypes.STRING,
  }),
};
